APIFiles/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/googaldiscal'

   root 'home#index'

end

APIFiles/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

APIFiles/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if params[:technology] && params[:location]
  		technology=params[:technology]
  		location=params[:location]
  		url = "http://api.indeed.com/ads/apisearch?v=2&format=json&co=in&limit=25&publisher=7277146494571922"
  		response=HTTParty.get("#{url}&q=#{technology}&l=#{location}")
  		@result=JSON.parse(response.body)
  	end	
  end

  def googaldiscal
  	if params[:origin] && params[:destination]
  		origin=params[:origin]
  		destination=params[:destination]
  		url="http://maps.googleapis.com/maps/api/distancematrix/json?mode=driving&language=en-EN&origins=#{origin}&destinations=#{destination}"
  		response=HTTParty.get("#{url}")
  		@result=JSON.parse(response.body)
  	end	
  end	
end

APIFiles/app/helpers/application_helper.rb
module ApplicationHelper
end

APIFiles/app/helpers/home_helper.rb
module HomeHelper
end

APIFiles/app/views/home/googaldiscal.html.erb
<h2>Find your dream job</h2>
<%= form_tag home_googaldiscal_path,method: :get do %>

	<label>Technology</label><br/>
	<%= text_field_tag :origin%> <br/><br/>

	<label>Locatin</label><br/>
	<%= text_field_tag :destination%><br/><br/>

	<%=submit_tag "Search.."%>

<%end%>



<% unless @result.nil? %>
	<b>Origin :</b><%=@result["origin_addresses"].join(",")%>
	<b>Destination :</b><%=@result["destination_addresses"].join(",")%>
	<b>Distance :</b> <%=@result["rows"][0]["elements"][0]["distance"]["text"]%><br/>
	<b>Travl Time : </b><%=@result["rows"][0]["elements"][0]["duration"]["text"]%><br/>
<%end%>	

APIFiles/app/views/home/index.html.erb
<h2>Find your dream job</h2>
<%= form_tag home_index_path,method: :get do %>

	<label>Technology</label><br/>
	<%= text_field_tag :technology%> <br/><br/>

	<label>Locatin</label><br/>
	<%= text_field_tag :location%><br/><br/>

	<%=submit_tag "Search.."%>

<%end%>

<% if !@result.nil? %>
	<h2>We found <%= @result["totalResults"] %> jobs for you in <%= params["location"]%> </h2>
	<table border="1">
		<thead>
			<tr>
				<th>Title</th>
				<th>Company</th>
				<th>Description</th>
			</th>
		</thead>
		<tbody>
			<% @result["results"].each do |job|%> <!--job is returns hash ,@result is hash And results is an array %>-->
			<tr>	
				<td><%=job["jobtitle"] %></td>	
				<td><%=job["company"] %></td>	
				<td><%=job["snippet"] %></td>
			</tr>
			
			<%end%>
		
		</tbody>
	</table>	
<% end %>					

APIFiles/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>APIFiles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>